inherit_from: https://raw.githubusercontent.com/rails/rails/master/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  DisabledByDefault: true

Rails/IndexBy:
  Enabled: false # until we support Rails version 6.0
