language: ruby
sudo: false
cache: bundler

rvm:
  - 3.0.3
  - 2.7.5
  - ruby-head
  - jruby-head

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  include:
    - rvm: 2.6.9
      env: BRANCH=6-0-stable
    - rvm: 2.7.5
      env: BRANCH=6-0-stable
    - rvm: 2.6.9
      env: BRANCH=6-0-stable
    - rvm: 2.7.5
      env: BRANCH=6-1-stable
    - rvm: 3.0.3
      env: BRANCH=6-1-stable
    - rvm: 2.7.5
      env: BRANCH=7-0-stable
    - rvm: 3.0.3
      env: BRANCH=7-0-stable

notifications:
  email: false
